#!/bin/sh

SCRIPT="$(dirname "$0")/pre-commit.py"
for pyCommand in python3 python py; do
    if command -v "$pyCommand" 2>&1; then
        # Check if this is a valid Python interpreter
        "$pyCommand" -c "import sys" 2>&1
        if [ $? -ne 0 ]; then
            continue
        fi

        # If we got here, the interpeter was valid, so run the script and report the exit code it returns
        "$pyCommand" "$SCRIPT"
        exit $?
    fi
done

echo "No suitable Python interpreter found on PATH"
exit 1