#!/bin/sh

if command -v python3 2>&1; then
    python3 "$(dirname "$0")/pre-commit.py"
elif command -v python 2>&1; then
    python "$(dirname "$0")/pre-commit.py"
elif command -v py 2>&1; then
    py "$(dirname "$0")/pre-commit.py"
else
    echo "No suitable Python version found on PATH"
    exit 1
fi